[metadata]
name = steganography_tool
version = 0.1
author = MVenjoyer
author_email = ggg.gggyy@yandex.ru
description = simple LSB

[options]
packages = find:
install_requires =
    click
    pillow
    numpy

[options.entry_points]
console_scripts =
    steganography-tool = steganography_tool.cli:cli
